const countryCodes = [
  { code: "+1", label: "🇺🇸 USA" },
  { code: "+1", label: "🇨🇦 Canada" },
  { code: "+7", label: "🇷🇺 Russia" },
  { code: "+7", label: "🇰🇿 Kazakhstan" },
  { code: "+20", label: "🇪🇬 Egypt" },
  { code: "+27", label: "🇿🇦 South Africa" },
  { code: "+30", label: "🇬🇷 Greece" },
  { code: "+31", label: "🇳🇱 Netherlands" },
  { code: "+32", label: "🇧🇪 Belgium" },
  { code: "+33", label: "🇫🇷 France" },
  { code: "+34", label: "🇪🇸 Spain" },
  { code: "+36", label: "🇭🇺 Hungary" },
  { code: "+39", label: "🇮🇹 Italy" },
  { code: "+40", label: "🇷🇴 Romania" },
  { code: "+41", label: "🇨🇭 Switzerland" },
  { code: "+43", label: "🇦🇹 Austria" },
  { code: "+44", label: "🇬🇧 United Kingdom" },
  { code: "+45", label: "🇩🇰 Denmark" },
  { code: "+46", label: "🇸🇪 Sweden" },
  { code: "+47", label: "🇳🇴 Norway" },
  { code: "+48", label: "🇵🇱 Poland" },
  { code: "+49", label: "🇩🇪 Germany" },
  { code: "+51", label: "🇵🇪 Peru" },
  { code: "+52", label: "🇲🇽 Mexico" },
  { code: "+53", label: "🇨🇺 Cuba" },
  { code: "+54", label: "🇦🇷 Argentina" },
  { code: "+55", label: "🇧🇷 Brazil" },
  { code: "+56", label: "🇨🇱 Chile" },
  { code: "+57", label: "🇨🇴 Colombia" },
  { code: "+58", label: "🇻🇪 Venezuela" },
  { code: "+60", label: "🇲🇾 Malaysia" },
  { code: "+61", label: "🇦🇺 Australia" },
  { code: "+62", label: "🇮🇩 Indonesia" },
  { code: "+63", label: "🇵🇭 Philippines" },
  { code: "+64", label: "🇳🇿 New Zealand" },
  { code: "+65", label: "🇸🇬 Singapore" },
  { code: "+66", label: "🇹🇭 Thailand" },
  { code: "+81", label: "🇯🇵 Japan" },
  { code: "+82", label: "🇰🇷 South Korea" },
  { code: "+84", label: "🇻🇳 Vietnam" },
  { code: "+86", label: "🇨🇳 China" },
  { code: "+90", label: "🇹🇷 Turkey" },
  { code: "+91", label: "🇮🇳 India" },
  { code: "+92", label: "🇵🇰 Pakistan" },
  { code: "+93", label: "🇦🇫 Afghanistan" },
  { code: "+94", label: "🇱🇰 Sri Lanka" },
  { code: "+95", label: "🇲🇲 Myanmar" },
  { code: "+98", label: "🇮🇷 Iran" },
  { code: "+211", label: "🇸🇸 South Sudan" },
  { code: "+212", label: "🇲🇦 Morocco" },
  { code: "+213", label: "🇩🇿 Algeria" },
  { code: "+216", label: "🇹🇳 Tunisia" },
  { code: "+218", label: "🇱🇾 Libya" },
  { code: "+220", label: "🇬🇲 Gambia" },
  { code: "+221", label: "🇸🇳 Senegal" },
  { code: "+222", label: "🇲🇷 Mauritania" },
  { code: "+223", label: "🇲🇱 Mali" },
  { code: "+224", label: "🇬🇳 Guinea" },
  { code: "+225", label: "🇨🇮 Ivory Coast" },
  { code: "+226", label: "🇧🇫 Burkina Faso" },
  { code: "+227", label: "🇳🇪 Niger" },
  { code: "+228", label: "🇹🇬 Togo" },
  { code: "+229", label: "🇧🇯 Benin" },
  { code: "+230", label: "🇲🇺 Mauritius" },
  { code: "+231", label: "🇱🇷 Liberia" },
  { code: "+232", label: "🇸🇱 Sierra Leone" },
  { code: "+233", label: "🇬🇭 Ghana" },
  { code: "+234", label: "🇳🇬 Nigeria" },
  { code: "+235", label: "🇹🇩 Chad" },
  { code: "+236", label: "🇨🇫 Central African Republic" },
  { code: "+237", label: "🇨🇲 Cameroon" },
  { code: "+238", label: "🇨🇻 Cape Verde" },
  { code: "+239", label: "🇸🇹 Sao Tome and Principe" },
  { code: "+240", label: "🇬🇶 Equatorial Guinea" },
  { code: "+241", label: "🇬🇦 Gabon" },
  { code: "+242", label: "🇨🇬 Republic of the Congo" },
  { code: "+243", label: "🇨🇩 DR Congo" },
  { code: "+244", label: "🇦🇴 Angola" },
  { code: "+245", label: "🇬🇼 Guinea-Bissau" },
  { code: "+246", label: "🇮🇴 British Indian Ocean Territory" },
  { code: "+248", label: "🇸🇨 Seychelles" },
  { code: "+249", label: "🇸🇩 Sudan" },
  { code: "+250", label: "🇷🇼 Rwanda" },
  { code: "+251", label: "🇪🇹 Ethiopia" },
  { code: "+252", label: "🇸🇴 Somalia" },
  { code: "+253", label: "🇩🇯 Djibouti" },
  { code: "+254", label: "🇰🇪 Kenya" },
  { code: "+255", label: "🇹🇿 Tanzania" },
  { code: "+256", label: "🇺🇬 Uganda" },
  { code: "+257", label: "🇧🇮 Burundi" },
  { code: "+258", label: "🇲🇿 Mozambique" },
  { code: "+260", label: "🇿🇲 Zambia" },
  { code: "+261", label: "🇲🇬 Madagascar" },
  { code: "+262", label: "🇷🇪 Réunion" },
  { code: "+263", label: "🇿🇼 Zimbabwe" },
  { code: "+264", label: "🇳🇦 Namibia" },
  { code: "+265", label: "🇲🇼 Malawi" },
  { code: "+266", label: "🇱🇸 Lesotho" },
  { code: "+267", label: "🇧🇼 Botswana" },
  { code: "+268", label: "🇸🇿 Eswatini" },
  { code: "+269", label: "🇰🇲 Comoros" },
];

export default countryCodes;
